# Nom du service et port d'écoute
spring.application.name=catalogue-service
server.port=8081

# Configuration de la base de données en mémoire (ultra-légère)
spring.datasource.url=jdbc:h2:mem:cataloguedb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Création automatique des tables au lancement
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Activation de la console web H2 (très pratique pour montrer au prof que ça marche)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console